# Generated by Django 3.1.5 on 2021-08-30 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='Frequency_Day',
            new_name='Frequency_Days',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Frequency_Month',
            new_name='Frequency_Months',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Frequency_Week',
            new_name='Frequency_Weeks',
        ),
    ]
