# Generated by Django 3.1.5 on 2021-12-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20210830_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadWellPictureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='WellPics/noImage.jpg', null=True, upload_to='WellPics/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('well_nm', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
