# Generated by Django 3.1.5 on 2021-12-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_uploadwellpicturemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='Consistency',
            new_name='consistency',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Frequency_Days',
            new_name='daily_freq',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Frequency_Months',
            new_name='monthly_freq',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Amount',
            new_name='quan',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Recipe_List',
            new_name='recipe_name',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Remark',
            new_name='remark',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Amount_Measure',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Frequency_Weeks',
            new_name='weekly_freq',
        ),
        migrations.RemoveField(
            model_name='table',
            name='SrNo',
        ),
    ]
