# Generated by Django 3.1.5 on 2021-12-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20211216_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='recipe_name',
            field=models.CharField(blank=True, default='WellPics/noImage.jpg', max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='uploadwellpicturemodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='WellPics/'),
        ),
    ]
