# Generated by Django 3.1.5 on 2021-12-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_auto_20211216_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadwellpicturemodel',
            name='picture',
            field=models.ImageField(blank=True, default='WellPics/noImage.jpg', null=True, upload_to='WellPics/'),
        ),
    ]
