# Generated by Django 3.1.5 on 2021-12-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_auto_20211216_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadwellpicturemodel',
            name='picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='WellPics/'),
        ),
    ]
