# Generated by Django 3.1.5 on 2021-12-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_auto_20211218_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.TextField(blank=True, default='Test', null=True)),
                ('daily_freq', models.IntegerField(default=1)),
                ('weekly_freq', models.IntegerField(default=1)),
                ('monthly_freq', models.IntegerField(default=2)),
                ('quan', models.IntegerField(default=3)),
                ('unit', models.CharField(blank=True, default='pieces', max_length=122, null=True)),
                ('consistency', models.CharField(blank=True, default='thick', max_length=122, null=True)),
                ('remark', models.TextField(blank=True, default='Test', null=True)),
            ],
        ),
    ]
